import {  createSlice } from '@reduxjs/toolkit';


const initialState = {
  nav:'Location',
  activity: '',
};


export const locationSlice = createSlice({
  name: 'Login',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    
    // Use the PayloadAction type to declare the contents of `action.payload`
    changePanel: (state, action) => {
      state.nav = action.payload;
    },

    selectActivity: (state, action) =>{
        state.activity = action.payload
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
 
});

export const {changePanel, selectActivity} = locationSlice.actions;

//


// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.



export default locationSlice.reducer;
